### ISSUE TITLE
Move Postcss 8 to peer deps

### ISSUE THREAD

**Issue by equinusocio** [csstools/postcss-inset#4]
Following the [PostCSS 8 migration guidelines](https://evilmartians.com/chronicles/postcss-8-plugin-migration), Postcss should be defined as peer dependency, and not as a public dependency.

**Comment by Antonio-Laguna** [comment]
@equinusocio thanks for reaching out! This plugin got superseeded by [postcss-logical](https://github.com/csstools/postcss-plugins/tree/main/plugins/postcss-logical). I will be archiving this repository soon!

**Comment by equinusocio** [comment]
Oh, oks!
