### ISSUE TITLE
Bump to 2.0.0

### ISSUE THREAD

**Issue by lmoval** [csstools/postcss-inset#5]
Hi, having https://github.com/csstools/postcss-inset/pull/2 being merged since a while.

Could you start taking care of the versioning of this repo?

My suggestions:
- Tag 1.0.0 at b3cf37e
- Bump major version (and at the same time update CHANGELOG.md), as bumping postcss to ^8.x.x represents a breaking change
- Tag 2.0.0 the new commit created ad the previous step

**Comment by Antonio-Laguna** [comment]
Hi, @lmoval thanks for bringing this up!

This plugin has been softly deprecated by `postcss-logical` which it's currently maintained here: https://github.com/csstools/postcss-plugins/tree/main/plugins/postcss-logical#logical-offsets which does what this plugin used to do and much more. 

As of now, we're not actively maintaining anything that's not within the `postcss-plugins` repo or `cssdb` repo.

Hope you can move to using `postcss-logical` and if you find any issues there we'd love to help :)

**Comment by lmoval** [comment]
Great! Thank you for your advice

I'm having a look at it ASAP!

**Comment by lmoval** [comment]
Great! Thank you for your advice

I'm having a look at it ASAP!
